```{r}
<<<<<<< HEAD
=======


>>>>>>> fa611856b585eb67dfe1fd0ecacafbc2585b929c
# Library Used for M3 Project
#####################################
library(magrittr) ## Fetching magnittr
library(knitr)
library(plyr)
library(dplyr)
library(readxl)
library(gridExtra)
# library(CGPfunctions)
library(RColorBrewer)
library(lattice)
library(ggplot2)
library(DT)
library(kableExtra)
library(ggpubr)
<<<<<<< HEAD
```

```{r}
# Create a data frame with the given data
data <- data.frame(
    SBP = c(109.6, 107.4, 140.3, 146.5, 98.2, 137.8, 124.1, 113.2, 127.8, 125.3, 108.5, 181.3, 137.4, 146.2, 142.4, 123.7, 129.6, 143.6, 160.7, 148.3),
    Hrs_day = c(7, 8, 9, 12, 6, 9, 10, 8, 9, 8, 6, 13, 10, 10, 9, 8, 8, 9, 11, 9),
    Area = c("east", "east", "east", "east", "east", "east", "east", "east", "east", "east", "west", "west", "west", "west", "west", "west", "west", "west", "west", "west")
)

# Fit a linear regression model
model <- lm(SBP ~ Hrs_day + Area, data = data)

# Print the regression equation
summary(model)$coefficients
=======



X <- (65 - 19) / 65
X
SE <- sqrt((X * (1 - X)) / 65)
SE

Y <- (X - 0.66) / SE
Y

z <- 8 - 2 * 0.54
z
```

```{r}

A <- c(19, 16, 14, 18, 19)

B <- c(25, 18, 27, 11, 23)

C <- mean(A)
D <- mean(B)

C
D
pnorm(0.05, lower.tail = FALSE)


alpha <- 0.002
cv1 <- qnorm(0.002 / 2)
cv2 <- qnorm(1 - (0.002 / 2))

cv1
cv2
>>>>>>> fa611856b585eb67dfe1fd0ecacafbc2585b929c
```