




```{r warning=FALSE, message=FALSE}
## Load the Library Used
library(magrittr)
library(knitr)
library(tidyverse)
library(plyr)
library(dplyr)
library(readxl)
library(gridExtra)
library(RColorBrewer)
library(lattice)
library(ggplot2)
library(corrplot)
library(summarytools)
library(DT)
library(kableExtra)
library(DescTools)
library(qcc)
library(agricolae)
library(car)
library(tidyverse)
library(RColorBrewer)
library(corrplot)
library(psych)
library(dplyr)
library(ggplot2)
library(gtools)
library(ggfortify)
library(GGally)
library(readr)
library(readxl)
library(knitr)
library(modelr)
library(scales)
library(lmtest)
library(olsrr)
library(leaps)
library(tibble)
library(sjPlot)
library(performance)
library(see)


# Load the data
Ames <- read_csv("~/Desktop/Intro To Analytics - ALY 6000/ALY 6000 - Project/Data Sets/AmesHousing.csv")


# Disabling scientific notation, so my graphs and outputs will be more readable:
options(scipen = 100)

# 2. Perform Exploratory Data Analysis and use descriptive statistics to describe the data.
###########################################################################
# Histogram of prices
ggplot(Ames, aes(x = SalePrice)) +
    geom_histogram(color = "black", fill = "#ed610b", bins = 50) +
    labs(title = "Distribution of house prices", x = "Price", y = "Frequency") +
    theme_minimal()

barplot(table(Ames$"Yr Sold"),
    main = "When were the most houses Sold?",
    xlab = "Year",
    ylab = "Number of houses",
    col = brewer.pal(9, "Blues")
)


barplot(table(Ames$"Overall Qual"),
    main = "In what Quality are the most houses on the market?",
    xlab = "Year",
    ylab = "Number of houses",
    col = brewer.pal(10, "RdYlBu")
)


# Histogram of Lot area
ggplot(Ames, aes_string(x = "`Lot Area`")) +
    geom_histogram(color = "black", fill = "#2c0ce6", bins = 30) +
    scale_x_continuous(labels = comma) +
    labs(title = "Distribution of House Lot Area", x = "Living area (sqft)", y = "Frequency") +
    theme_minimal()

# Let's see median prices per neighborhood
neighbourhoods <- tapply(Ames$SalePrice, Ames$Neighborhood, median)
neighbourhoods <- sort(neighbourhoods, decreasing = TRUE)

dotchart(neighbourhoods,
    pch = 21, bg = "purple1",
    cex = 0.85,
    xlab = "Average price of a house",
    main = "Which neighborhood is the most expensive to buy a house in?"
)




# Firstly, I'd like to check the missing values
na_count <- sapply(Ames, function(Ames) sum(length(which(is.na(Ames)))))

na_count

# 3. Imputation of Mean Value in "Mas Vnr Area" Variable
#################################################################
Ames$"Mas Vnr Area"[is.na(Ames$"Mas Vnr Area")] <- mean(Ames$"Mas Vnr Area", na.rm = TRUE)


na_count <- sapply(Ames, function(Ames) sum(length(which(is.na(Ames)))))

na_count


# 4. Use the "cor()" function to produce a correlation matrix of the numeric values.
###################################################################################

# Creating data subset without character variables
data.only.numeric <- Ames[, !sapply(Ames, is.character)]

only.numeric.noNA <- na.omit(data.only.numeric)



correlation.matrix <- cor(only.numeric.noNA, method = "pearson")


# Rounding off the digits in Table
table2 <- round((correlation.matrix), digits = 2)


# Present the table using kableExta Package
knitr::kable(table2,
    caption = "Table 2: Descriptive Statistics of MPG Data Set Using
    Code psych::describe () ",
    format = "html",
    table.attr = "style=width: 40%",
    font_size = 8
) %>%
    kable_styling(bootstrap_options = c(
        "striped", "hover",
        "condensed", "responsive"
    )) %>%
    kable_classic(
        full_width = F,
        html_font = "Times New Roman"
    )



# 5. Produce a plot of the correlation matrix, and explain how to interpret it.
###################################################################################
corrplot::corrplot(cor(correlation.matrix), tl.cex = 0.5)


# 6. Make a scatter plot for the X continuous variable with the highest correlation with
# SalePrice. Do the same for the X variable that has the lowest correlation with SalePrice.
# Finally, make a scatter plot between X and SalePrice with the correlation closest to 0.5. Interpret the scatter plots and describe how the patterns differ.


# Variable with highest correlation with SalePrice
################################################

# Creating Objects for Analysis
YSalePrice <- c(Ames$SalePrice)
XOverallQuality <- c(Ames$`Overall Qual`)


# Using the linear Regression Formula
linearReg2.6 <- lm(YSalePrice ~ XOverallQuality)

# Creatinng an object to store the summary of the linear regression
SumData2.6 <- summary(linearReg2.6)

# Extracting Values and Creating Object to store the value of Intercept and Slope
Intercept2.6 <- SumData2.6$coefficients[[1]]

Slope2.6 <- SumData2.6$coefficients[[2]]

# Plotting the Scatter Plot
plot(
    YSalePrice ~ XOverallQuality,
    pch = 19,
    col = "blue",
    xlab = "Overall Quality",
    ylab = "Sales Price",
    main = "Linear Regression: Overall Quality and Sale Price "
)


# Adding Lines and Text in Scatter Plot
abline(linearReg2.6, col = "#99004C", lty = 2, lwd = 2) # Adding the Regression Line

abline(v = 0, lwd = 2)

abline(h = 0, lwd = 2)



# Variable with lowest correlation with SalePrice
################################################

# Creating Objects for Analysis
YSalePrice <- c(Ames$SalePrice)
XMiscVal <- c(Ames$`Misc Val`)


# Using the linear Regression Formula
linearReg2.7 <- lm(YSalePrice ~ XMiscVal)

# Creatinng an object to store the summary of the linear regression
SumData2.6 <- summary(linearReg2.7)

# Extracting Values and Creating Object to store the value of Intercept and Slope
Intercept2.6 <- SumData2.6$coefficients[[1]]

Slope2.6 <- SumData2.6$coefficients[[2]]

# Plotting the Scatter Plot
plot(
    YSalePrice ~ XMiscVal,
    pch = 19,
    col = "#ff6600",
    xlab = "Miscellaneous feature",
    ylab = "Sales Price",
    main = "Linear Regression: Miscellaneous feature and Sale Price "
)


# Adding Lines and Text in Scatter Plot
abline(linearReg2.7, col = "#99004C", lty = 2, lwd = 2) # Adding the Regression Line

abline(v = 0, lwd = 2)

abline(h = 0, lwd = 2)


# 7. Variable with a correlation closest to 0.5
###############################################


# Creating Objects for Analysis
YSalePrice <- c(Ames$SalePrice)
XTotRmsAbvGrd <- c(Ames$`TotRms AbvGrd`)


# Using the linear Regression Formula
linearReg2.8 <- lm(YSalePrice ~ XTotRmsAbvGrd)

# Creatinng an object to store the summary of the linear regression
SumData2.6 <- summary(linearReg2.8)

# Extracting Values and Creating Object to store the value of Intercept and Slope
Intercept2.6 <- SumData2.6$coefficients[[1]]

Slope2.6 <- SumData2.6$coefficients[[2]]

# Plotting the Scatter Plot
plot(
    YSalePrice ~ XTotRmsAbvGrd,
    pch = 19,
    col = "#f6055d",
    xlab = "Total rooms above grade",
    ylab = "Sales Price",
    main = "Linear Regression: Total rooms above grade and Sale Price "
)


# Adding Lines and Text in Scatter Plot
abline(linearReg2.8, col = "#99004C", lty = 2, lwd = 2) # Adding the Regression Line

abline(v = 0, lwd = 2)

abline(h = 0, lwd = 2)



# 7. Using at least 3 continuous variables, fit a regression model in R.

# a. Creating regression model
# Selecting variables

attach(only.numeric.noNA)
Table_regression <- lm(SalePrice ~ `Garage Area` + `Gr Liv Area` + `Total Bsmt SF`)
tab_model(Table_regression)



summary(Table_regression)


# b. Plotting regression model
par(mfrow = c(2, 2))
plot(Table_regression)




# 10. Checking the model for multicollinearity
######################################
vif(Table_regression)


# 11. Looking for unusual observations or outliers
#############################################
outlierTest(model = Table_regression)

hat.plot <- function(fit) {
    p <- length(coefficients(Table_regression))
    n <- length(fitted(Table_regression))
    plot(hatvalues(Table_regression), main = "Index Plot of hat Values")
    abline(h = c(2, 3) * p / n, col = "red", lty = 2)
    identify(1:n, hatvalues(Table_regression), names(hatvalues(Table_regression)))
}

ols_plot_cooksd_chart(Table_regression)

par(mfrow = c(1, 1))
hat.plot(Table_regression)
```

```{r warning=FALSE, message=FALSE}
# 12. Eliminating unusual observations to improve model
#############################################
cooksd <- cooks.distance(Table_regression)
sample_size <- nrow(data.only.numeric)
influential <- as.numeric(names(cooksd)[(cooksd > (4 / sample_size))])
only.numeric.no.outliers <- only.numeric.noNA[-influential, ]


# a. Looking at model now
attach(only.numeric.no.outliers)

Table_regression2 <- lm(SalePrice ~ `Garage Area` + `Gr Liv Area` + `Total Bsmt SF`)


par(mfrow = c(2, 2))
plot(Table_regression2)


summary(Table_regression2)


# 12. Attempt to correct any issues that you have discovered in your model. Did your changes improve the model, why or why not?


par(mfrow = c(1, 1))

hist(data.only.numeric$SalePrice)


hist(only.numeric.no.outliers$SalePrice)
```

```{r}
# 13. Use the all subsets regression method to identify the "best" model.
########################################################################


regfit_full <- regsubsets(SalePrice ~ ., data = only.numeric.noNA)

# a. Looking at the model selected by subsets method
model2 <- lm(SalePrice ~ `Overall Qual` + `BsmtFin SF 1` + `Gr Liv Area`)
summary(model2)


plot(model2)


# 14. Compare the preferred model from step 13 with your model from step 12
#########################################################################
compare_performance(Table_regression2, model2, rank = TRUE)

plot(compare_performance(Table_regression2, model2, rank = TRUE))
```